http:
 #region routers 
  routers:
    proxmox:
      entryPoints:
        - "https"
      rule: "Host(`proxmox.venenga.net`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: proxmox
    truenas:
      entryPoints:
        - "https"
      rule: "Host(`truenas.venenga.net`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: truenas
    pterodactyl:
      entryPoints:
        - "https"
      rule: "Host(`pterodactyl.venenga.net`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: pterodactyl

#endregion
#region services
  services:
    proxmox:
      loadBalancer:
        servers:
          - url: "https://10.20.0.8:8006"
        passHostHeader: true
    truenas:
      loadBalancer:
        servers:
          - url: "https://10.20.0.10"
        passHostHeader: true
    pterodactyl:
      loadBalancer:
        servers:
          - url: "http://10.40.0.160"
        passHostHeader: true
#endregion
  middlewares:
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true

    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    idrac:
      headers:
        frameDeny: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https


    secured:
      chain:
        middlewares:
        - default-headers